### ISSUE TITLE
Support ':' in slugs

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#107]
### Environment
* Python version:  
* Peering Manager version:  

### Proposed Functionality

Add `:` to the list of supported slug characters

### Use Case

My current policies all use `:` as a delimiter instead of `-` or `_`.

**Comment by respawner** [comment]
In Django by definition a slug cannot contain `:`. Slugs are mostly designed to be URL friendly and are most of the time configuration friendly as well (the way I see it at least).

I'm not in favor of introducing `:` as a valid slug character for routing policies. We can discuss about this to fix the issue that you are facing though.

You could use the `name` field of the routing policy to match your need instead of the `slug` maybe?

**Comment by jlixfeld** [comment]
No problem.  It's not the end of the world if I have to rename my route policies.  However, using `name` might be a reasonable alternative.  I'll look into that.  Thank you!
