### ISSUE TITLE
Ability to work with logical-systems for junos

### ISSUE THREAD

**Issue by mirackle-spb** [respawner/peering-manager#210]
### Proposed Functionality
Will be good to have ability to work with logical-systems on juniper routers. It`s just simple. need to place "set cli logical-system LOGICAL-SYSTEM-NAME-HERE" at start of dialog. and than all other commands will be executed within logical router context.

Some times need to split physical host to some virtual. This feature will make possible automatic peer configuration.

**Comment by jlixfeld** [comment]
I would imagine you could get the functionality you are after using BGP groups that you could then reference in a configuration template, couldn't you?

**Comment by respawner** [comment]
I suppose that there several ways to achieve this:

1. Logical systems being "logical routers", you could create one router instance in Peering Manager per logical system and attach it a configuration template
2. You could use a tag to identify the logical system an IX or BGP group is supposed to belong to

I'd prefer using option number one since it a bit more flexible in my opinion.

**Comment by mirackle-spb** [comment]
Not relevant. You can close it. Found a direct solution without crutches.
