### ISSUE TITLE
Filtering fields with double '_' in Internet Exchange Peering Session List API

### ISSUE THREAD

**Issue by kzorba** [respawner/peering-manager#257]
Hello,

hopefully I use the correct category of issue for this. Using the API to retrieve Internet Exchange peering lists I wanted to filter with the Internet Exchange ID. My code did not work as expected until I noticed that the field name that should be passed to the API is `internet_exchange__id` (notice the double underscore in the field name).
The same is true for other fields like `autonomous_system__id` or `autonomous_system__asn`

### Proposed Changes
 I think the filter field names should be changed to include single underscores to avoid bugs in the API usage.

**Comment by respawner** [comment]
This is actually not a bug but a feature. This is the way django-filters knows how to find which part is the model and which part is the field of the model. This behavior is internal to django-filters and cannot be altered or at least won't be because I don't intend to rewrite a filter mechanism on my own :D

**Comment by kzorba** [comment]
Thanks for the info, I can consider that the API is steady as it is then :)
