### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by omershtivi** [respawner/peering-manager#43]
### Issue type
[ X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* Peering Manager version:  

### Description

Add a plugin location, where we can integrate plugins that are not part of the core system. Currently I have to plugins I want to develop but I don't think they are part of the core:
1. Collect flow information from flow collector API to get how match traffic do the network has we a specific peer.
2. External web site that can be exposed to public users allowing them to setup peering with the router automatically (example company X would like to peer with my company, they fill their information, peering-manager generates config and push to the router)

**Comment by respawner** [comment]
I guess this feature is actually two.

The first one is about allowing the collection of data from other tools. I doubt it could be simple to implement because it depends on what kind of tools and mostly on how to integrate these tools in the UI. So I guess it is a bit out of the scope of this project.

The second one is directly linked with issue #41. It would allow an external website to make API calls on Peering Manager so it can handle the peering setup part automatically.
